### ISSUE TITLE
Memory consumption for large Databases

### ISSUE THREAD

**Issue by mburri** [sfa-siard/JdbcPostgres#5] opened 2023-04-28 13:53 UTC
Archiving large PosgresQL Databases needs lots of memory and leads to java.lang.OutOfMemory excpetions:

`Herunterladen der Datenbank gescheitert (  org.postgresql.util.PSQLException: Ran out of memory retrieving query results.< java.lang.OutOfMemoryError: Java heap space)! Unvollständiges SIARD-Archiv wird gelöscht`

Increasing the available heap space helps - but the performance still degrades drastically.
The problem is specific to PostgresSQL - other DBMS like MsSQL Server are not affected.

See also: https://github.com/sfa-siard/SiardGui/issues/61 and https://github.com/sfa-siard/SiardGui/issues/60

**Comment by Amasit** [comment] 2023-11-20 13:46
Duplicate of https://github.com/sfa-siard/SiardGui/issues/60

**Closed by Amasit** 2023-11-20 13:46 UTC
Labels: bug, duplicate
